@ECHO off
SET APPNAME=reports
SET BRANCH=feature
SET ENV=PSQAA
SET CONT=NA
SET RELEASE=%APPNAME%_%VERSION%
SET RELEASE_PATH=X:\%APPNAME%\%BRANCH%\%RELEASE%
SET UNC_RELEASE_PATH=\\ec2-54-82-242-72.compute-1.amazonaws.com\releases

ECHO.
ECHO VERSION:      %VERSION%
ECHO APPNAME:      %APPNAME%
ECHO BRANCH:       %BRANCH%
ECHO ENV:          %ENV%
ECHO CONT:         %CONT%
ECHO RELEASE:      %RELEASE%
ECHO RELEASE_PATH: %RELEASE_PATH%
ECHO.

IF NOT EXIST "X:\" (
   NET USE X: %UNC_RELEASE_PATH% /persistent:yes
)

IF NOT EXIST "%RELEASE_PATH%" (
   ECHO "FATAL ERROR: %RELEASE_PATH% does not exist."
   EXIT /B 1
)

PUSHD %RELEASE_PATH%

CALL DEPLOY.SSRS.CMD %ENV% %CONT%

POPD